### ISSUE TITLE
amazon-cognito-identity-js incompatible version

### ISSUE THREAD

**Issue by xintellion** [webiny/webiny-js#1817]
## This is:
* Bug

## Specifications
* version: 5.11.0
* OS: *
* Browser: *

## Expected Behavior
The amazon-cognito-identity-js versions of the root package.json and the one required by amplify should be compatible

## Actual Behavior
I'm using @aws-amplify/auth (^4.0.2)  in one of my packages, after upgrading to 5.11.0 the packages doesn't build anymore

` ../../node_modules/@webiny/app-security-cognito-authentication/node_modules/amazon-cognito-identity-js/index.d.ts(1,1): error TS6200: Definitions of the following identifiers conflict with those in another file: ClientMetadat
a, AuthenticationDetails, CognitoUser, CognitoUserAttribute, CognitoUserPool, CognitoUserSession, CognitoAccessToken, CognitoIdToken, CognitoRefreshToken, CookieStorage, UserAgent, appendToCognitoUserAgent, WordArray`

## Detailed Description
@aws-amplify/auth (^4.0.2 -> 4.1.3) has a depenedeny to "amazon-cognito-identity-js": "^5.0.0", but the root package.json has a dependeny to "amazon-cognito-identity-js": "^4.5.3". Those two versions seem not to be compatible.

**Comment by Pavel910** [comment]
@xintellion thanks, we'll see if we can update to the newer Amplify Auth package.
