### ISSUE TITLE
Unable to build after upgrading from 5.21.0 to 5.22.0

### ISSUE THREAD

**Issue by snstanton** [webiny/webiny-js#2214]
### Version

5.22.0

### Operating System

MacOS

### Browser

Firefox

### What steps will reproduce the bug?

My project builds and deploys normally under 5.21.0.
After running the upgrade steps (`yarn up ...` and `yarn webiny upgrade`), the build no longer succeeds.  Instead, I get this error:
```
@connect/connect-graphql: webiny error: ../../node_modules/@types/eslint-scope/node_modules/@types/eslint/helpers.d.ts(1,6): error TS2300: Duplicate identifier 'Prepend'.
../../node_modules/@types/eslint/helpers.d.ts(1,6): error TS2300: Duplicate identifier 'Prepend'.
```
If I manually remove the directory `node_modules/@types/eslint-scope/node_modules/@types/eslint/`, I can get past this failure, and successfully `api`.  However, when I try to deploy my application, I get errors because the scss files are no longer able to resolve image file paths in the public directory.

Additionally, trying to deploy `apps/admin` generates this error:
```
Failed to load plugin '@typescript-eslint' declared in '../../../.eslintrc.js': Class extends value undefined is not a constructor or null
Referenced from: /Users/scotts/workspace/connect/.eslintrc.js
Failed to compile.
```

I have tried removing node_modules completely and rerunning `yarn install` with the same result.

**Comment by Pavel910** [comment]
@snstanton I updated the upgrade script with the missing dep version upgrades. Run `yarn webiny upgrade` again and see if builds after that. I also left some comments in the Slack thread.
